import {
    LayoutDashboard,
    Users,
    GraduationCap,
    Building2,
    Briefcase,
    ShieldCheck,
    CalendarCheck,
    Award,
    BarChart3,
    Settings,
    History,
    Landmark,
    Target,
    BookOpen,
    UserCheck,
    Handshake,
    ServerCog,
} from 'lucide-react';
import type { AdminNavItem } from '../../types/admin';

export const ADMIN_NAVIGATION: AdminNavItem[] = [

    // ─── System Admin ───
    {
        path: '/admin/system-admin',
        label: 'System Admin Dashboard',
        icon: ServerCog,
        section: 'Overview',
        allowedRoles: ['system_admin'],
    },
    {
        path: '/admin/users',
        label: 'User Management',
        icon: Users,
        section: 'Directory',
        allowedRoles: ['system_admin'],
    },
    {
        path: '/admin/students',
        label: 'Students Directory',
        icon: GraduationCap,
        section: 'Directory',
        allowedRoles: ['system_admin'],
    },
    {
        path: '/admin/batch-analytics',
        label: 'Batch Analytics',
        icon: BarChart3,
        section: 'Directory',
        allowedRoles: ['system_admin'],
    },
    {
        path: '/admin/eligibility-rules',
        label: 'Eligibility Rules',
        icon: ShieldCheck,
        section: 'System Configuration',
        allowedRoles: ['system_admin'],
    },
    {
        path: '/admin/reports',
        label: 'Reports & Analytics',
        icon: BarChart3,
        section: 'Insights',
        allowedRoles: ['system_admin'],
    },
    {
        path: '/admin/settings',
        label: 'Platform Settings',
        icon: Settings,
        section: 'System',
        allowedRoles: ['system_admin'],
    },
    {
        path: '/admin/audit-logs',
        label: 'Audit Logs',
        icon: History,
        section: 'System',
        allowedRoles: ['system_admin'],
    },

    // ─── Dean ───
    {
        path: '/admin/dean',
        label: 'Dean Dashboard',
        icon: Landmark,
        section: 'Overview',
        allowedRoles: ['dean'],
    },
    {
        path: '/admin/dashboard',
        label: 'Overview Dashboard',
        icon: LayoutDashboard,
        section: 'Overview',
        allowedRoles: ['dean'],
    },
    {
        path: '/admin/users',
        label: 'User Management',
        icon: Users,
        section: 'Directory',
        allowedRoles: ['dean'],
    },
    {
        path: '/admin/students',
        label: 'Students Directory',
        icon: GraduationCap,
        section: 'Directory',
        allowedRoles: ['dean'],
    },
    {
        path: '/admin/batch-analytics',
        label: 'Batch Analytics',
        icon: BarChart3,
        section: 'Directory',
        allowedRoles: ['dean'],
    },
    {
        path: '/admin/reports',
        label: 'Reports & Analytics',
        icon: BarChart3,
        section: 'Insights',
        allowedRoles: ['dean'],
    },
    {
        path: '/admin/settings',
        label: 'Platform Settings',
        icon: Settings,
        section: 'System',
        allowedRoles: ['dean'],
    },
    {
        path: '/admin/audit-logs',
        label: 'Audit Logs',
        icon: History,
        section: 'System',
        allowedRoles: ['dean'],
    },

    // ─── Director ───
    {
        path: '/admin/director',
        label: 'Director Dashboard',
        icon: Target,
        section: 'Overview',
        allowedRoles: ['director'],
    },
    {
        path: '/admin/dashboard',
        label: 'Overview Dashboard',
        icon: LayoutDashboard,
        section: 'Overview',
        allowedRoles: ['director'],
    },
    {
        path: '/admin/users',
        label: 'User Management',
        icon: Users,
        section: 'Directory',
        allowedRoles: ['director'],
    },
    {
        path: '/admin/students',
        label: 'Students Directory',
        icon: GraduationCap,
        section: 'Directory',
        allowedRoles: ['director'],
    },
    {
        path: '/admin/batch-analytics',
        label: 'Batch Analytics',
        icon: BarChart3,
        section: 'Directory',
        allowedRoles: ['director'],
    },
    {
        path: '/admin/reports',
        label: 'Reports & Analytics',
        icon: BarChart3,
        section: 'Insights',
        allowedRoles: ['director'],
    },
    {
        path: '/admin/settings',
        label: 'Platform Settings',
        icon: Settings,
        section: 'System',
        allowedRoles: ['director'],
    },
    {
        path: '/admin/audit-logs',
        label: 'Audit Logs',
        icon: History,
        section: 'System',
        allowedRoles: ['director'],
    },

    // ─── Program Chair ───
    {
        path: '/admin/program-chair',
        label: 'Program Chair Dashboard',
        icon: BookOpen,
        section: 'Overview',
        allowedRoles: ['program_chair'],
    },
    {
        path: '/admin/dashboard',
        label: 'Overview Dashboard',
        icon: LayoutDashboard,
        section: 'Overview',
        allowedRoles: ['program_chair'],
    },
    {
        path: '/admin/users',
        label: 'User Management',
        icon: Users,
        section: 'Directory',
        allowedRoles: ['program_chair'],
    },
    {
        path: '/admin/students',
        label: 'Students Directory',
        icon: GraduationCap,
        section: 'Directory',
        allowedRoles: ['program_chair'],
    },
    {
        path: '/admin/batch-analytics',
        label: 'Batch Analytics',
        icon: BarChart3,
        section: 'Directory',
        allowedRoles: ['program_chair'],
    },
    {
        path: '/admin/reports',
        label: 'Reports & Analytics',
        icon: BarChart3,
        section: 'Insights',
        allowedRoles: ['program_chair'],
    },
    {
        path: '/admin/settings',
        label: 'Platform Settings',
        icon: Settings,
        section: 'System',
        allowedRoles: ['program_chair'],
    },
    {
        path: '/admin/audit-logs',
        label: 'Audit Logs',
        icon: History,
        section: 'System',
        allowedRoles: ['program_chair'],
    },

    // ─── Faculty ───
    {
        path: '/admin/faculty',
        label: 'Faculty Dashboard',
        icon: UserCheck,
        section: 'Overview',
        allowedRoles: ['faculty'],
    },
    {
        path: '/admin/users',
        label: 'User Management',
        icon: Users,
        section: 'Directory',
        allowedRoles: ['faculty'],
    },
    {
        path: '/admin/students',
        label: 'Students Directory',
        icon: GraduationCap,
        section: 'Directory',
        allowedRoles: ['faculty'],
    },
    {
        path: '/admin/batch-analytics',
        label: 'Batch Analytics',
        icon: BarChart3,
        section: 'Directory',
        allowedRoles: ['faculty'],
    },
    {
        path: '/admin/settings',
        label: 'Platform Settings',
        icon: Settings,
        section: 'System',
        allowedRoles: ['faculty'],
    },
    {
        path: '/admin/audit-logs',
        label: 'Audit Logs',
        icon: History,
        section: 'System',
        allowedRoles: ['faculty'],
    },

    // ─── Placement Officer ───
    {
        path: '/admin/placement-officer',
        label: 'Placement Officer Dashboard',
        icon: Handshake,
        section: 'Overview',
        allowedRoles: ['placement_officer'],
    },
    {
        path: '/admin/companies',
        label: 'Companies',
        icon: Building2,
        section: 'Placement Operations',
        allowedRoles: ['placement_officer'],
    },
    {
        path: '/admin/drives',
        label: 'Placement Drives',
        icon: Briefcase,
        section: 'Placement Operations',
        allowedRoles: ['placement_officer'],
    },
    {
        path: '/admin/interviews',
        label: 'Interviews',
        icon: CalendarCheck,
        section: 'Placement Operations',
        allowedRoles: ['placement_officer'],
    },
    {
        path: '/admin/offers',
        label: 'Offers & Outcomes',
        icon: Award,
        section: 'Placement Operations',
        allowedRoles: ['placement_officer'],
    },
    {
        path: '/admin/reports',
        label: 'Reports & Analytics',
        icon: BarChart3,
        section: 'Insights',
        allowedRoles: ['placement_officer'],
    },
    {
        path: '/admin/settings',
        label: 'Platform Settings',
        icon: Settings,
        section: 'System',
        allowedRoles: ['placement_officer'],
    },
    {
        path: '/admin/audit-logs',
        label: 'Audit Logs',
        icon: History,
        section: 'System',
        allowedRoles: ['placement_officer'],
    },
];
